import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { TRPCReactProvider } from "@/trpc/client";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      appearance={{
        elements: {
          card: {
            boxShadow: "none",
            border: "none",
            backgroundColor: "transparent",
            width: "100%",
            maxWidth: "600px",
          },
          cardBox: {
            boxShadow: "none",
            border: "none",
            backgroundColor: "transparent",
            width: "100%",
            maxWidth: "600px",
          },
          rootBox: {
            boxShadow: "none",
            backgroundColor: "transparent",
            width: "100%",
            maxWidth: "600px",
          },
          modalContent: {
            boxShadow: "none",
            border: "none",
            backgroundColor: "transparent",
          },
          socialButtonsBlockButton: {
            boxShadow: "none",
          },
          formFieldInput: {
            boxShadow: "none",
          },
          footer: {
            boxShadow: "none",
            backgroundColor: "transparent",
          },
          headerTitle: {
            boxShadow: "none",
          },
          identityPreview: {
            boxShadow: "none",
          },
          formButtonPrimary: {
            boxShadow: "none",
          },
          navbar: {
            boxShadow: "none",
            backgroundColor: "transparent",
          },
          navbarButton: {
            boxShadow: "none",
          },
          pageScrollBox: {
            boxShadow: "none",
            backgroundColor: "transparent",
          },
          page: {
            boxShadow: "none",
            backgroundColor: "transparent",
          },
        },
      }}
    >
      <TRPCReactProvider>
        <html lang="en" suppressHydrationWarning>
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            suppressHydrationWarning
          >
            {children}
          </body>
        </html>
      </TRPCReactProvider>
    </ClerkProvider>
  );
}
