import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import { Geist_Mono, Manrope } from "next/font/google";
import "./globals.css";
import { TRPCReactProvider } from "@/trpc/client";
import { Toaster } from "@/components/ui/sonner";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import { TooltipProvider } from "@/components/ui/tooltip";
const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      appearance={{
        variables: {
          colorPrimary: "#203AFB",
          colorPrimaryForeground: "#ffffff",
          colorBackground: "#ffffff",
          colorForeground: "#030A18",
          colorMutedForeground: "#545E7E",
          colorInputBackground: "#ffffff",
          colorInputForeground: "#030A18",
          colorNeutral: "#0A1428",
          fontFamily: "var(--font-manrope), sans-serif",
          borderRadius: "0.625rem",
        },
        elements: {
          card: {
            boxShadow: "none",
            border: "none",
            backgroundColor: "transparent",
            width: "100%",
            maxWidth: "600px",
          },
          cardBox: {
            boxShadow: "none",
            border: "none",
            backgroundColor: "transparent",
            width: "100%",
            maxWidth: "600px",
          },
          rootBox: {
            boxShadow: "none",
            backgroundColor: "transparent",
            width: "100%",
            maxWidth: "600px",
          },
          modalContent: {
            boxShadow: "none",
            border: "none",
            backgroundColor: "transparent",
          },
          socialButtonsBlockButton: {
            boxShadow: "none",
          },
          formFieldInput: {
            boxShadow: "none",
          },
          footer: {
            boxShadow: "none",
            backgroundColor: "transparent",
          },
          headerTitle: {
            boxShadow: "none",
          },
          identityPreview: {
            boxShadow: "none",
          },
          formButtonPrimary: {
            boxShadow: "none",
          },
          navbar: {
            boxShadow: "none",
            backgroundColor: "transparent",
          },
          navbarButton: {
            boxShadow: "none",
          },
          pageScrollBox: {
            boxShadow: "none",
            backgroundColor: "transparent",
          },
          page: {
            boxShadow: "none",
            backgroundColor: "transparent",
          },
        },
      }}
    >
      <TRPCReactProvider>
        <html lang="en" suppressHydrationWarning>
          <body
            className={`${manrope.variable} ${geistMono.variable} min-h-screen antialiased`}
            suppressHydrationWarning
          >
            <NuqsAdapter>
              <Toaster />
              <TooltipProvider>{children}</TooltipProvider>
            </NuqsAdapter>
          </body>
        </html>
      </TRPCReactProvider>
    </ClerkProvider>
  );
}
